// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Sample REST API
This is a sample api


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 1.0.0
    License: MIT httpshttps://github.com/sakata1222/go-rest-api-sample/blob/master/LICENSE

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
