swagger: "2.0"
info:
  description: "This is a sample api"
  version: "1.0.0"
  title: "Sample REST API"
  license:
    name: "MIT"
    url: "httpshttps://github.com/sakata1222/go-rest-api-sample/blob/master/LICENSE"
paths:
  /user/{userId}:
    get:
      summary: "get a user"
      description: "return the specified"
      parameters:
        - name: "userId"
          in: "path"
          description: "the id of a user"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "Response"
          schema:
            type: "object"
            properties:
              id:
                type: "integer"
                format: "int64"
              name:
                type: "string"
                example: "name"
